[package]
name = "dots"
version = "0.1.0"
authors = ["AusCyber <willp@outlook.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# git2 = "0.13"
anyhow = "1.0.38"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
clap = "2.33.3"
structopt = { version = "0.3" }
directories = "3.0"
