name: build

on:
  push:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'Cargo.lock'

  pull_request:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**.rs'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            target/**/build
          key: ${{ runner.os }}-${{ hashFiles('Cargo.*') }}
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/release/dots
