name: build

on:
  push:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'src/**.rs'

  pull_request:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'src/**.rs'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
        with:
          name: binary
          path: target/release/dots
