name: build

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'src'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
        with:
          name: binary
          path:
              target/release/dots
