name: release

on: workflow_dispatch



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check release version
        id: version-check
        uses: thebongy/version-check@v1
        with:
          file: Cargo.toml
          tagFormat: v${version}

      - run: rustup default nightly
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: dots-binary
          path: target/release/dots
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/dots
          draft: true
          tag_name: ${{ steps.version-check.outputs.releaseVersion }}
          body_path: CHANGES.md
