name: tests

on:
  push:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'Cargo.lock'
  pull_request:
    branches: [ master ]
    paths:
      - 'Cargo.toml'
      - 'src/**.rs'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
             ~/.cargo/bin/
             ~/.cargo/registry/index/
             ~/.cargo/registry/cache/
             ~/.cargo/git/db/
             target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup default nightly
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings


  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: |
           ~/.cargo/bin/
           ~/.cargo/registry/index/
           ~/.cargo/registry/cache/
           ~/.cargo/git/db/
           target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup default nightly
    - run: cargo test --verbose

